version: '3'
services:
  app:
    container_name: tasktime_app
    build: .
    ports:
      - 8500:8500 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    volumes:
      - api:/home/gouser/goserve/
    depends_on:
      - postgres # This service depends on postgres. Start that first
    networks:
      - tasktimenetwork

  postgres:
    image: postgres:latest
    container_name: tasktime_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - tasktimenetwork

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  tasktimenetwork: