version: "3.9"

services:

  postgres:
    image: postgres
    container_name: timetracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timetracker
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - time_tracker_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: timetracker_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: colddevelop@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - time_tracker_network
    restart: unless-stopped
    depends_on:
      - postgres

  app:
    container_name: timetracker_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    restart: on-failure
    volumes:
      - app:/app
    depends_on:
      - postgres
    networks:
      - time_tracker_network

networks:
  time_tracker_network:
    driver: bridge