basePath: /api/v1
host: localhost:8500
info:
  contact: {}
  description: Документация по сервису тайм трекера
  title: Time Tracker API
  version: "1"
paths:
  /users/create:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя
      produces:
      - application/json
      responses: {}
      security:
      - bearerToken: []
      summary: Создает нового пользователя
      tags:
      - Users
swagger: "2.0"
