definitions:
  controller.userResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
    type: object
  model.TaskCreate:
    properties:
      description:
        example: Описание задачи
        type: string
      title:
        example: Новая задача
        type: string
    type: object
  model.TaskResponse:
    properties:
      description:
        type: string
      end_date:
        type: string
      period_time:
        type: string
      start_date:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  model.User:
    properties:
      address:
        example: г. Москва, ул. Ленина, д. 5, кв. 1
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        example: Иван
        type: string
      passportNumber:
        type: integer
      passportSeries:
        type: integer
      patronymic:
        example: Иванович
        type: string
      surname:
        example: Иванов
        type: string
      updated_at:
        type: string
    type: object
  model.UserCreate:
    properties:
      address:
        example: г. Москва, ул. Ленина, д. 5, кв. 1
        type: string
      name:
        example: Иван
        type: string
      passportNumber:
        example: 1234 567890
        type: string
      patronymic:
        example: Иванович
        type: string
      surname:
        example: Иванов
        type: string
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: 'Status: Bad Request'
        type: string
    type: object
  utils.HTTPSuccess:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: 'Status: OK'
        type: string
    type: object
  utils.Pagination:
    properties:
      limit:
        type: integer
      page:
        type: integer
      rows: {}
      sort:
        type: string
      total_pages:
        type: integer
      total_rows:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/tasks/countdown/end/{tid}:
    patch:
      consumes:
      - application/json
      description: Закончить отсчет времени по задаче для пользователя
      parameters:
      - description: ID задачи
        in: path
        name: tid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.HTTPSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Закончить отсчет времени по задаче для пользователя
      tags:
      - Задачи
  /api/v1/tasks/countdown/start/{uid}:
    post:
      consumes:
      - application/json
      description: Начать отсчет времени по задаче для пользователя
      parameters:
      - description: ID пользователя
        in: path
        name: uid
        required: true
        type: string
      - description: Описание задачи
        in: body
        name: task
        schema:
          $ref: '#/definitions/model.TaskCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.HTTPSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Начать отсчет времени по задаче для пользователя
      tags:
      - Задачи
  /api/v1/tasks/info/{uid}:
    get:
      consumes:
      - application/json
      description: Получение трудозатрат по пользователю за период задача-сумма часов
        и минут
      parameters:
      - description: ID пользователя
        in: path
        name: uid
        required: true
        type: string
      - default: 2024-07-01T00:00:00
        description: Начальная дата
        in: query
        name: startDate
        required: true
        type: string
      - default: 2024-07-01T23:59:59
        description: Конечная дата
        in: query
        name: endDate
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.TaskResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Получение трудозатрат по пользователю
      tags:
      - Задачи
  /api/v1/users/delete/{id}:
    delete:
      description: Изменение данных пользователя
      parameters:
      - description: Идентификатор пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.HTTPSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Удаление пользователя
      tags:
      - Пользователи
  /api/v1/users/find/{id}:
    get:
      consumes:
      - application/json
      description: Получение данных о пользователе по ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.userResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Получение данных о пользователе по ID
      tags:
      - Пользователи
  /api/v1/users/info:
    get:
      consumes:
      - application/json
      description: Получение данных о пользователе по серии и номеру паспорта
      parameters:
      - description: Поиск по серии паспорта
        in: query
        name: passportSeries
        required: true
        type: integer
      - description: Поиск по номеру паспорта
        in: query
        name: passportNumber
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.userResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Получение данных о пользователе по паспорту
      tags:
      - Пользователи
  /api/v1/users/list:
    get:
      consumes:
      - application/json
      description: Получение данных о всех пользователях
      parameters:
      - default: "1"
        description: Укажите с какой страницы смотреть
        in: query
        name: page
        type: string
      - default: "10"
        description: Укажите какое количество выводить
        in: query
        name: limit
        type: string
      - description: Сортировать данные
        example: asc, desc
        in: query
        name: sort
        type: string
      - description: Поле для сортировки
        example: Id, Surname, Name, Patronymic, Address, PassportSeries, PassportNumber
        in: query
        name: field
        type: string
      - description: Поиск по полям
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Pagination'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Получение данных о всех пользователях
      tags:
      - Пользователи
  /api/v1/users/update/{id}:
    patch:
      consumes:
      - application/json
      description: Изменение данных пользователя
      parameters:
      - description: Идентификатор пользователя
        in: path
        name: id
        required: true
        type: string
      - description: Изменение данных пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.HTTPSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Изменение данных пользователя
      tags:
      - Пользователи
  /users/create:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя
      parameters:
      - description: Новый пользователь
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserCreate'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.userResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Создает нового пользователя
      tags:
      - Пользователи
swagger: "2.0"
